### ISSUE TITLE
 Could not find a matching version of package seandowney/backpackstorecrud

### ISSUE THREAD

**Issue by DanielKimmich** [seandowney/laravel-backpack-store-crud#1]
I execute composer require seandowney/backpackstorecrud

Error:
 [InvalidArgumentException]                                                                                                            
 Could not find a matching version of package seandowney/backpackstorecrud. Check the package spelling, your version constraint and tha
 t the package is available in a stability which matches your minimum-stability (dev).

**Comment by seandowney** [comment]
That's a bit of a problem alright!

I'll have to set that up later.

**Comment by seandowney** [comment]
@DanielKimmich It's been a long time since I looked at this but I have a 1.0.x version now :D 

You're probably not interested in this anymore though.
